### ISSUE TITLE
btrfs qgroup command failed

### ISSUE THREAD

**Issue by ramelito** [cloudfoundry-incubator/garden-linux-release#14]
Hi, i am observing errors with btrfs qgroup action. GLR is 0.307

{"timestamp":"1446201139.823039770","source":"garden-linux","message":"garden-linux.btrfs-cleanup.clean-rootfs.remove-qgroup.command.failed","l
og_level":2,"data":{"argv":["btrfs","qgroup","show","-f","/var/vcap/data/garden/btrfs_graph/btrfs/subvolumes/3a5bce3189ae34acfde14dc4f2bcfcbb76
00910fd58588348f23eb32e001454c"],"error":"exit status 1","exit-status":1,"id":"48mg2k0l8g9","session":"1.2793.2.1","stderr":"ERROR: can't perfo
rm the search - No such file or directory\nERROR: can't list qgroups: No such file or directory\n","stdout":"","took":"5.15829ms"}}

**Comment by julz** [comment]
Hi @ramelito - are you running inside a bosh-lite environment? I think we've seen some issues with btrfs quotas when garden is running in a container due to the way btrfs works in a nested context. FYI the latest garden-linux-release (as of v0.326.0) uses aufs rather than btrfs as its layered filesystem, and a different approach to enforcing quotas.

**Comment by ramelito** [comment]
@julz Hi, i've read release notes for GLR 0.326.0, right now we are running on GLR 0.307.0
deployment is done over openstack with boshrelease

**Comment by goonzoid** [comment]
@ramelito is this still an issue for you, or are you able to upgrade to the latest version (which we'd highly recommend)?

**Comment by goonzoid** [comment]
@ramelito I'm going to close this. Since the announcement of CVE-2015-5350 yesterday, it's not recommended to be running any version of garden-linux-release before v0.330.0. This version no longer uses btrfs, so this shouldn't be a problem any more.

Feel free to reopen if there's some reason that you really still need to run the older version.
