### ISSUE TITLE
Can not execute busybox

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry-incubator/garden-linux-release#16]
The busybox in garden-linux-release v0.327.0 can not execute in stemcell bosh-openstack-kvm-ubuntu-trusty-go_agent 3137.

```
root@647f793e-0814-4b8a-9722-4224319501ac:/var/vcap/packages/busybox# /var/vcap/packages/busybox/bin/busybox ls
bash: /var/vcap/packages/busybox/bin/busybox: No such file or directory
```

But the file exists and it looks executable.

```
root@647f793e-0814-4b8a-9722-4224319501ac:/var/vcap/packages/busybox# ls -al /var/vcap/packages/busybox/bin/busybox
-rwsr-xr-x 1 root root 561992 May 22  2014 /var/vcap/packages/busybox/bin/busybox
root@647f793e-0814-4b8a-9722-4224319501ac:/var/vcap/packages/busybox# file /var/vcap/packages/busybox/bin/busybox
/var/vcap/packages/busybox/bin/busybox: setuid ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), stripped
```
However busybox command is linked to libc.so.0, but it does not exist.

```
root@647f793e-0814-4b8a-9722-4224319501ac:/var/vcap/packages/busybox# ldd /var/vcap/packages/busybox/bin/busybox
        linux-vdso.so.1 =>  (0x00007ffd183fd000)
        libc.so.0 => not found
```

Currently we can choose [default container rootfs](https://github.com/cloudfoundry-incubator/garden-linux-release/blob/97067ba6271f0c7fea29f26d863794acfdde604a/jobs/garden/spec#L52-L54).
However in many cases, we use cflinuxfs2 as rootfs.
So I think that delete busybox from garden-linux-release and should set cflinuxfs2 as default.

**Comment by goonzoid** [comment]
Hi @kei-yamazaki 

The busybox package is used as the default rootfs for the garden server in a default deployment of garden-linux-release. This means it is never executed directly on the host, but becomes the root file system of containers (if not overridden). The error you see above is due to the libc.so.0 library not being found because this library is part of the busybox package, and not part of ubuntu. IOW: it works when executed inside a busybox container, rather than directly on the host.

We include busybox because it's small and simple. We don't want the burden of keeping in sync with developments in the cflinuxfs2 rootfs, and that rootfs is in fact only useful in the Cloud Foundry use case. Other users of Garden-Linux (such as Concourse) would have no need for it.

If you're having trouble creating containers, I'd recommend starting with the [Example Use](https://github.com/cloudfoundry-incubator/garden#example-use) section of the Garden client README.
